;;; poimandres-common.el --- Shared faces for the Poimandres themes -*- lexical-binding: t; -*-

;; Author: kamm3r <https://github.com/kamm3r>
;; URL: https://github.com/kamm3r/poimandres.el
;; Version: 0.2.0
;; Package-Requires: ((emacs "25.1"))

;;; Commentary:
;; Palettes and face definitions shared by `poimandres-theme.el' and
;; `poimandres-storm-theme.el'.  Colors follow the Poimandres VS Code
;; theme (https://github.com/drcmda/poimandres-theme).  VS Code colors
;; with an alpha channel are pre-blended against each variant's
;; background, since Emacs faces cannot be translucent.

;;; Code:

(require 'let-alist)

(defconst poimandres-palettes
  '((poimandres
     (bg . "#1b1e28") (focus . "#303340") (selection . "#272c3c")
     (gray . "#a6accd") (darker-gray . "#767c9d")
     (bluish-gray . "#506477") (bluish-gray-brighter . "#7390AA")
     (desaturated-blue . "#91B4D5") (lower-blue . "#89ddff")
     (light-blue . "#ADD7FF") (mint . "#5DE4c7") (lower-mint . "#5fb3a1")
     (bluish-green . "#42675A") (yellow . "#fffac2") (red . "#d0679d")
     (pink . "#f087bd") (off-white . "#e4f0fb") (white . "#ffffff")
     (comment . "#5a5f79") (line-number . "#383b4d")
     (function-call . "#bfc9d4") (type . "#8489a4")
     (added-bg . "#243137") (removed-bg . "#322737")
     (added-refine-bg . "#2c4346") (removed-refine-bg . "#483045"))
    (poimandres-storm
     (bg . "#252b37") (focus . "#404350") (selection . "#32394b")
     (gray . "#a6accd") (darker-gray . "#868cad")
     (bluish-gray . "#607487") (bluish-gray-brighter . "#7390AA")
     (desaturated-blue . "#91B4D5") (lower-blue . "#89ddff")
     (light-blue . "#ADD7FF") (mint . "#5DE4c7") (lower-mint . "#5fb3a1")
     (bluish-green . "#42675A") (yellow . "#fffac2") (red . "#d0679d")
     (pink . "#f087bd") (off-white . "#e4f0fb") (white . "#ffffff")
     (comment . "#686e88") (line-number . "#43495c")
     (function-call . "#c1ccd7") (type . "#868ca8")
     (added-bg . "#2c3c44") (removed-bg . "#3a3344")
     (added-refine-bg . "#344d52") (removed-refine-bg . "#503a51")))
  "Color palettes for each Poimandres theme variant.")

(defun poimandres-theme-set-faces (theme)
  "Set the faces of THEME using its palette from `poimandres-palettes'."
  (let ((class '((class color) (min-colors 89))))
    (let-alist (alist-get theme poimandres-palettes)
      (custom-theme-set-faces
       theme
       ;; Editor
       `(default ((,class (:foreground ,.gray :background ,.bg))))
       `(cursor ((,class (:background ,.gray))))
       `(fringe ((,class (:background ,.bg))))
       `(region ((,class (:background ,.focus :extend t))))
       `(secondary-selection ((,class (:background ,.selection :extend t))))
       `(highlight ((,class (:background ,.focus))))
       `(hl-line ((,class (:background ,.selection :extend t))))
       `(match ((,class (:background ,.light-blue :foreground ,.bg))))
       `(isearch ((,class (:background ,.light-blue :foreground ,.bg :weight bold))))
       `(isearch-fail ((,class (:background ,.red :foreground ,.off-white))))
       `(lazy-highlight ((,class (:background ,.focus :foreground ,.light-blue))))
       `(show-paren-match ((,class (:background ,.focus :foreground ,.off-white :weight bold))))
       `(show-paren-mismatch ((,class (:background ,.red :foreground ,.off-white))))
       `(link ((,class (:foreground ,.light-blue :underline t))))
       `(link-visited ((,class (:foreground ,.desaturated-blue :underline t))))
       `(shadow ((,class (:foreground ,.darker-gray))))
       `(minibuffer-prompt ((,class (:foreground ,.lower-blue :weight bold))))
       `(vertical-border ((,class (:foreground ,.focus))))
       `(window-divider ((,class (:foreground ,.focus))))
       `(header-line ((,class (:background ,.focus :foreground ,.gray))))
       `(tooltip ((,class (:background ,.focus :foreground ,.gray))))
       `(error ((,class (:foreground ,.red))))
       `(warning ((,class (:foreground ,.yellow))))
       `(success ((,class (:foreground ,.mint))))
       ;; Syntax
       `(font-lock-builtin-face ((,class (:foreground ,.mint))))
       `(font-lock-comment-face ((,class (:foreground ,.comment :slant italic))))
       `(font-lock-comment-delimiter-face ((,class (:inherit font-lock-comment-face))))
       `(font-lock-doc-face ((,class (:foreground ,.comment :slant italic))))
       `(font-lock-doc-markup-face ((,class (:foreground ,.bluish-gray-brighter :slant italic))))
       `(font-lock-constant-face ((,class (:foreground ,.mint))))
       `(font-lock-function-name-face ((,class (:foreground ,.light-blue))))
       `(font-lock-function-call-face ((,class (:foreground ,.function-call))))
       `(font-lock-keyword-face ((,class (:foreground ,.desaturated-blue :slant italic))))
       `(font-lock-negation-char-face ((,class (:foreground ,.red))))
       `(font-lock-operator-face ((,class (:foreground ,.desaturated-blue))))
       `(font-lock-string-face ((,class (:foreground ,.mint))))
       `(font-lock-escape-face ((,class (:foreground ,.lower-mint))))
       `(font-lock-regexp-grouping-backslash ((,class (:foreground ,.lower-mint :weight bold))))
       `(font-lock-regexp-grouping-construct ((,class (:foreground ,.lower-mint :weight bold))))
       `(font-lock-number-face ((,class (:foreground ,.mint))))
       `(font-lock-variable-name-face ((,class (:foreground ,.off-white))))
       `(font-lock-variable-use-face ((,class (:foreground ,.off-white))))
       `(font-lock-type-face ((,class (:foreground ,.type))))
       `(font-lock-property-name-face ((,class (:foreground ,.off-white))))
       `(font-lock-property-use-face ((,class (:foreground ,.off-white))))
       `(font-lock-punctuation-face ((,class (:foreground ,.gray))))
       `(font-lock-bracket-face ((,class (:foreground ,.gray))))
       `(font-lock-delimiter-face ((,class (:foreground ,.gray))))
       `(font-lock-preprocessor-face ((,class (:foreground ,.mint))))
       `(font-lock-warning-face ((,class (:foreground ,.red :weight bold))))
       ;; Layout, whitespace, and line numbers
       `(line-number ((,class (:foreground ,.line-number :background ,.bg))))
       `(line-number-current-line ((,class (:foreground ,.gray :background ,.bg))))
       `(mode-line ((,class (:foreground ,.gray :background ,.bg
                                         :box (:line-width 1 :color ,.focus)))))
       `(mode-line-inactive ((,class (:foreground ,.darker-gray :background ,.bg
                                                  :box (:line-width 1 :color ,.focus)))))
       `(mode-line-buffer-id ((,class (:foreground ,.off-white :weight bold))))
       `(mode-line-emphasis ((,class (:foreground ,.mint :weight bold))))
       `(mode-line-highlight ((,class (:foreground ,.light-blue))))
       `(border ((,class (:background ,.bg))))
       `(trailing-whitespace ((,class (:background ,.red))))
       `(whitespace-space ((,class (:foreground ,.focus :background ,.bg))))
       `(whitespace-tab ((,class (:foreground ,.focus :background ,.bg))))
       `(whitespace-newline ((,class (:foreground ,.focus :background ,.bg))))
       `(whitespace-trailing ((,class (:foreground ,.pink :background ,.bg))))
       `(whitespace-line ((,class (:foreground ,.pink :background ,.bg))))
       ;; Diagnostics
       `(flymake-error ((,class (:underline (:style wave :color ,.red)))))
       `(flymake-warning ((,class (:underline (:style wave :color ,.yellow)))))
       `(flymake-note ((,class (:underline (:style wave :color ,.light-blue)))))
       `(flycheck-error ((,class (:underline (:style wave :color ,.red)))))
       `(flycheck-warning ((,class (:underline (:style wave :color ,.yellow)))))
       `(flycheck-info ((,class (:underline (:style wave :color ,.light-blue)))))
       `(compilation-error ((,class (:foreground ,.red :weight bold))))
       `(compilation-warning ((,class (:foreground ,.yellow))))
       `(compilation-info ((,class (:foreground ,.light-blue))))
       ;; Diff and version control
       `(diff-added ((,class (:foreground ,.light-blue :background ,.added-bg :extend t))))
       `(diff-removed ((,class (:foreground ,.desaturated-blue :background ,.removed-bg :extend t))))
       `(diff-changed ((,class (:foreground ,.desaturated-blue :extend t))))
       `(diff-refine-added ((,class (:background ,.added-refine-bg))))
       `(diff-refine-removed ((,class (:background ,.removed-refine-bg))))
       `(diff-indicator-added ((,class (:foreground ,.lower-mint))))
       `(diff-indicator-removed ((,class (:foreground ,.red))))
       `(diff-header ((,class (:foreground ,.lower-blue :background ,.focus))))
       `(diff-file-header ((,class (:foreground ,.off-white :weight bold))))
       `(diff-hl-insert ((,class (:foreground ,.lower-mint :background ,.lower-mint))))
       `(diff-hl-change ((,class (:foreground ,.light-blue :background ,.light-blue))))
       `(diff-hl-delete ((,class (:foreground ,.red :background ,.red))))
       `(git-gutter:added ((,class (:foreground ,.lower-mint))))
       `(git-gutter:modified ((,class (:foreground ,.light-blue))))
       `(git-gutter:deleted ((,class (:foreground ,.red))))
       ;; Completion and navigation
       `(completions-common-part ((,class (:foreground ,.mint))))
       `(completions-first-difference ((,class (:foreground ,.light-blue))))
       `(company-tooltip ((,class (:foreground ,.gray :background ,.focus))))
       `(company-tooltip-selection ((,class (:foreground ,.off-white :background ,.bluish-gray))))
       `(company-tooltip-common ((,class (:foreground ,.mint))))
       `(company-scrollbar-bg ((,class (:background ,.focus))))
       `(company-scrollbar-fg ((,class (:background ,.gray))))
       `(vertico-current ((,class (:background ,.focus :foreground ,.off-white))))
       `(orderless-match-face-0 ((,class (:foreground ,.mint :weight bold))))
       `(orderless-match-face-1 ((,class (:foreground ,.light-blue :weight bold))))
       `(orderless-match-face-2 ((,class (:foreground ,.yellow :weight bold))))
       `(orderless-match-face-3 ((,class (:foreground ,.pink :weight bold))))
       `(ivy-current-match ((,class (:background ,.focus :foreground ,.off-white))))
       `(ivy-minibuffer-match-face-1 ((,class (:foreground ,.mint))))
       `(ivy-minibuffer-match-face-2 ((,class (:foreground ,.light-blue :weight bold))))
       `(ivy-minibuffer-match-face-3 ((,class (:foreground ,.yellow :weight bold))))
       `(ivy-minibuffer-match-face-4 ((,class (:foreground ,.pink :weight bold))))
       ;; Org and Markdown
       `(org-level-1 ((,class (:foreground ,.light-blue :weight bold))))
       `(org-level-2 ((,class (:foreground ,.lower-blue :weight bold))))
       `(org-level-3 ((,class (:foreground ,.mint :weight bold))))
       `(org-level-4 ((,class (:foreground ,.desaturated-blue))))
       `(org-link ((,class (:foreground ,.light-blue :underline t))))
       `(org-code ((,class (:foreground ,.light-blue))))
       `(org-verbatim ((,class (:foreground ,.light-blue))))
       `(org-block ((,class (:background ,.selection :extend t))))
       `(org-quote ((,class (:slant italic))))
       `(org-warning ((,class (:foreground ,.yellow))))
       `(org-done ((,class (:foreground ,.mint))))
       `(org-todo ((,class (:foreground ,.red :weight bold))))
       `(markdown-header-face ((,class (:foreground ,.off-white :weight bold))))
       `(markdown-markup-face ((,class (:foreground ,.light-blue))))
       `(markdown-inline-code-face ((,class (:foreground ,.light-blue))))
       `(markdown-code-face ((,class (:background ,.selection :extend t))))
       `(markdown-language-keyword-face ((,class (:foreground ,.desaturated-blue))))
       `(markdown-link-face ((,class (:foreground ,.light-blue))))
       `(markdown-url-face ((,class (:foreground ,.light-blue :underline t))))
       `(markdown-italic-face ((,class (:foreground ,.bluish-gray-brighter :slant italic))))
       `(markdown-bold-face ((,class (:foreground ,.bluish-gray-brighter :weight bold))))
       `(markdown-blockquote-face ((,class (:slant italic))))
       `(markdown-list-face ((,class (:foreground ,.light-blue))))
       ;; Dired
       `(dired-directory ((,class (:foreground ,.light-blue :weight bold))))
       `(dired-flagged ((,class (:foreground ,.red))))
       `(dired-marked ((,class (:foreground ,.yellow :weight bold))))
       ;; Magit
       `(magit-branch-local ((,class (:foreground ,.mint))))
       `(magit-branch-remote ((,class (:foreground ,.lower-mint))))
       `(magit-section-heading ((,class (:foreground ,.lower-blue :weight bold))))
       `(magit-hash ((,class (:foreground ,.yellow))))
       `(magit-diff-added ((,class (:foreground ,.light-blue :background ,.added-bg :extend t))))
       `(magit-diff-removed ((,class (:foreground ,.desaturated-blue :background ,.removed-bg :extend t))))
       `(magit-diff-added-highlight ((,class (:foreground ,.light-blue :background ,.added-refine-bg :extend t))))
       `(magit-diff-removed-highlight ((,class (:foreground ,.desaturated-blue :background ,.removed-refine-bg :extend t))))
       ;; Web mode
       `(web-mode-doctype-face ((,class (:foreground ,.mint))))
       `(web-mode-html-tag-bracket-face ((,class (:foreground ,.off-white))))
       `(web-mode-html-tag-face ((,class (:foreground ,.mint))))
       `(web-mode-html-attr-name-face ((,class (:foreground ,.lower-mint :slant italic))))
       `(web-mode-html-attr-equal-face ((,class (:foreground ,.gray))))
       `(web-mode-html-attr-value-face ((,class (:foreground ,.mint))))
       ;; Doom modeline
       `(doom-modeline-bar ((,class (:background ,.mint))))
       `(doom-modeline-info ((,class (:foreground ,.mint))))
       `(doom-modeline-urgent ((,class (:foreground ,.red))))
       `(doom-modeline-warning ((,class (:foreground ,.yellow))))
       `(doom-modeline-evil-normal-state ((,class (:foreground ,.bg :background ,.mint :weight bold))))
       `(doom-modeline-evil-insert-state ((,class (:foreground ,.bg :background ,.light-blue :weight bold))))
       `(doom-modeline-evil-visual-state ((,class (:foreground ,.bg :background ,.yellow :weight bold))))
       `(doom-modeline-evil-replace-state ((,class (:foreground ,.bg :background ,.red :weight bold))))
       ;; ANSI colors used by ansi-color-mode and terminal buffers
       `(ansi-color-black ((,class (:foreground ,.bg :background ,.bg))))
       `(ansi-color-red ((,class (:foreground ,.red :background ,.red))))
       `(ansi-color-green ((,class (:foreground ,.mint :background ,.mint))))
       `(ansi-color-yellow ((,class (:foreground ,.yellow :background ,.yellow))))
       `(ansi-color-blue ((,class (:foreground ,.lower-blue :background ,.lower-blue))))
       `(ansi-color-magenta ((,class (:foreground ,.pink :background ,.pink))))
       `(ansi-color-cyan ((,class (:foreground ,.lower-blue :background ,.lower-blue))))
       `(ansi-color-white ((,class (:foreground ,.white :background ,.white))))
       `(ansi-color-bright-black ((,class (:foreground ,.gray :background ,.gray))))
       `(ansi-color-bright-red ((,class (:foreground ,.red :background ,.red))))
       `(ansi-color-bright-green ((,class (:foreground ,.mint :background ,.mint))))
       `(ansi-color-bright-yellow ((,class (:foreground ,.yellow :background ,.yellow))))
       `(ansi-color-bright-blue ((,class (:foreground ,.light-blue :background ,.light-blue))))
       `(ansi-color-bright-magenta ((,class (:foreground ,.pink :background ,.pink))))
       `(ansi-color-bright-cyan ((,class (:foreground ,.light-blue :background ,.light-blue))))
       `(ansi-color-bright-white ((,class (:foreground ,.white :background ,.white))))))))

(provide 'poimandres-common)

;;; poimandres-common.el ends here
